version: "3.5"

services:
  island:
    image: r15ch13/arkcluster:latest
    env_file:
      - cluster.env
    environment:
      SERVERMAP: "TheIsland"
      SESSION_NAME: "Frost Cluster TheIsland"
      RCON_PORT: 32330
      GAME_PORT: 7777
      QUERY_PORT: 27015
    volumes:
      - server_island:/ark
      - cluster:/cluster
    ports:
      - "32330:32330/tcp"
      - "7777:7777/udp"
      - "7778:7778/udp"
      - "27015:27015/udp"

  valguero:
    image: r15ch13/arkcluster:latest
    env_file:
      - cluster.env
    environment:
      SERVERMAP: "Valguero_P"
      SESSION_NAME: "Frost Cluster Valguero"
      RCON_PORT: 32331
      GAME_PORT: 7779
      QUERY_PORT: 27016
    volumes:
      - server_valguero:/ark
      - cluster:/cluster
    ports:
      - "32331:32331/tcp"
      - "7779:7779/udp"
      - "7780:7780/udp"
      - "27016:27016/udp"

  abberation:
    image: r15ch13/arkcluster:latest
    env_file:
      - cluster.env
    environment:
      SERVERMAP: "Aberration_P"
      SESSION_NAME: "Frost Cluster Abberation"
      RCON_PORT: 32332
      GAME_PORT: 7781
      QUERY_PORT: 27017
    volumes:
      - server_abberation:/ark
      - cluster:/cluster
    ports:
      - "32332:32332/tcp"
      - "7781:7781/udp"
      - "7782:7782/udp"
      - "27017:27017/udp"

  extinction:
    image: r15ch13/arkcluster:latest
    env_file:
      - cluster.env
    environment:
      SERVERMAP: "Extinction"
      SESSION_NAME: "Frost Cluster Extinction"
      RCON_PORT: 32333
      GAME_PORT: 7783
      QUERY_PORT: 27018
    volumes:
      - server_extinction:/ark
      - cluster:/cluster
    ports:
      - "32333:32333/tcp"
      - "7783:7783/udp"
      - "7784:7784/udp"
      - "27018:27018/udp"

  ragnarok:
    image: r15ch13/arkcluster:latest
    env_file:
      - cluster.env
    environment:
      SERVERMAP: "Ragnarok"
      SESSION_NAME: "Frost Cluster Ragnarok"
      RCON_PORT: 32334
      GAME_PORT: 7785
      QUERY_PORT: 27019
    volumes:
      - server_ragnarok:/ark
      - cluster:/cluster
    ports:
      - "32334:32334/tcp"
      - "7785:7785/udp"
      - "7786:7786/udp"
      - "27019:27019/udp"

#  crystal:
#    image: r15ch13/arkcluster:latest
#    env_file:
#      - cluster.env
#    environment:
#      SERVERMAP: "CrystalIsles"
#      SESSION_NAME: "Frost Cluster CrystalIsles"
#      RCON_PORT: 32335
#      GAME_PORT: 7787
#      QUERY_PORT: 27020
#      MODS: "731604991,849985437,804312798"
#    volumes:
#      - server_crystal:/ark
#      - cluster:/cluster
#    ports:
#      - "32335:32335/tcp"
#      - "7787:7787/udp"
#      - "7788:7788/udp"
#      - "27020:27020/udp"

  center:
    image: r15ch13/arkcluster:latest
    env_file:
      - cluster.env
    environment:
      SERVERMAP: "TheCenter"
      SESSION_NAME: "Frost Cluster TheCenter"
      RCON_PORT: 32336
      GAME_PORT: 7789
      QUERY_PORT: 27021
    volumes:
      - server_center:/ark
      - cluster:/cluster
    ports:
      - "32336:32336/tcp"
      - "7789:7789/udp"
      - "7790:7790/udp"
      - "27021:27021/udp"

  scorched:
    image: r15ch13/arkcluster:latest
    env_file:
      - cluster.env
    environment:
      SERVERMAP: "ScorchedEarth_P"
      SESSION_NAME: "Frost Cluster ScorchedEarth"
      RCON_PORT: 32337
      GAME_PORT: 7791
      QUERY_PORT: 27022
    volumes:
      - server_scorched:/ark
      - cluster:/cluster
    ports:
      - "32337:32337/tcp"
      - "7791:7791/udp"
      - "7792:7792/udp"
      - "27022:27022/udp"

volumes:
  server_island:
  server_valguero:
  server_abberation:
  server_extinction:
  server_ragnarok:
#  server_crystal:
  server_center:
  server_scorched:
  cluster:

