#!/bin/bash

:'
This script can be used to backup all settings from each map on the cluster.
Be sure you have defined all maps in the MAP variable.
Create a backup dir in the local dir seperated for each map.
include the following configs:
 - arkmanager.cfg
 - Game.ini
 - GameUserSettings.ini

Keep in mind:
 - Game.ini is everywhere the same on the cluster
 - GameUserSettings generated by arkmanager and /ark/arkmanager.cfg. The default is located under /home/steam/arkmanager-user.cfg. Here are env vars so this will be sourced on loading
 - I have more env vars in arkmanager-user.cfg and another docker-compose file as in the github repo where the image come from
'

MAP="center ragnarok valguero extinction abberation island crystal scorched"

for map in $MAP
  do
	CONTAINER="ark_${map}_1"
	VOLUME="ark_server_${map}"
	BACKUP="$(pwd)/backup/$map"
	CONF="$(pwd)"

	if [ ! -d "$BACKUP" ]; then
	    mkdir -p $BACKUP
	fi

	echo "map: $map in volume: $VOLUME and container: $CONTAINER"
	docker exec -it ark_${map}_1 /bin/bash -c "arkmanager stop"
	# backup and overwrite Game.ini (all have the same)
	docker run -d --rm --name dummy -v $VOLUME:/root alpine tail -f /dev/null
	# Game.ini
	#docker cp dummy:/root/server/ShooterGame/Saved/Config/LinuxServer/Game.ini $BACKUP/Game.ini
	docker exec dummy /bin/sh -c 'rm /root/server/ShooterGame/Saved/Config/LinuxServer/Game.ini'
	docker cp ${CONF}/Game.ini dummy:/root/server/ShooterGame/Saved/Config/LinuxServer/Game.ini

	# arkmanager
	#docker cp dummy:/root/arkmanager.cfg $BACKUP/arkmanager.cfg
	docker exec dummy /bin/sh -c 'rm /root/arkmanager.cfg'
	docker cp ${CONF}/arkmanager-user.cfg dummy:/root/arkmanager.cfg

	docker stop dummy
	docker exec -it ark_${map}_1 /bin/bash -c "rm /ark/server/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini;arkmanager start"
done

echo "done"

exit 0
